### ISSUE TITLE
Is this package still being maintained? (A problem occurred evaluating project ':quiet')

### ISSUE THREAD

**Issue by NiccoloCase** [cawfree/react-native-quiet#31]
I'm trying to implement this very promising library but I'm getting various errors that don't allow me to finish the build successfully.
Specifically this is what I get:
```
$ npx react-native run-android
info Starting JS server...
info Installing the app...

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.5.1/userguide/command_line_interface.html#sec:command_line_warnings
5 actionable tasks: 5 up-to-date

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\coding\playground\quiet\node_modules\react-native-quiet\android\Transducer\quiet\build.gradle' line: 34

* What went wrong:
A problem occurred evaluating project ':quiet'.
> Could not find method compile() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

error Failed to install the app. Make sure you have the Android development environment set up: https://reactnative.dev/docs/environment-setup.
Error: Command failed: gradlew.bat app:installDebug -PreactNativeDevServerPort=8081

FAILURE: Build failed with an exception.

* Where:
Build file 'D:\coding\playground\quiet\node_modules\react-native-quiet\android\Transducer\quiet\build.gradle' line: 34

* What went wrong:
A problem occurred evaluating project ':quiet'.
> Could not find method compile() for arguments [directory 'libs'] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 7s

    at makeError (D:\coding\playground\quiet\node_modules\execa\index.js:174:9)
    at D:\coding\playground\quiet\node_modules\execa\index.js:278:16
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async runOnAllDevices (D:\coding\playground\quiet\node_modules\@react-native-community\cli-platform-android\build\commands\runAndroid\runOnAllDevices.js:109:5)
    at async Command.handleAction (D:\coding\playground\quiet\node_modules\@react-native-community\cli\build\index.js:142:9)
info Run CLI with --verbose flag for more details.
```

I don't know very much about android development and I hope someone can help me. 
Isn't it that these errors perhaps come from using an outdated package? 
Thanks in advance.

**Comment by johnilizy17** [comment]
Change all compile to implement
